/*
Name: Team 3
Date: 01 - 05 -18
This class is the interface that adds products and money to the machines
*/
package gui;

import logic.*;

import java.io.*;
import java.util.*;

public class Add extends javax.swing.JFrame {
    // Attributes for the first machine
    private User user;
    private ArrayList<Product> products= new ArrayList<Product>();
    private ArrayList<Integer> coins= new ArrayList<Integer>();
    private ArrayList<Integer> coins_introduced= new ArrayList<Integer>();
    private Machine machine1;
    private ObjectWriter machine_writer=new ObjectWriter();
    /// Attributes for the second machine
    private User user2;
    private ArrayList<Product> products2= new ArrayList<Product>();
    private ArrayList<Integer> coins2= new ArrayList<Integer>();
    private ArrayList<Integer> coins2_introduced= new ArrayList<Integer>();
    private Machine2 machine2;
    private ObjectWriter machine_writer2=new ObjectWriter();

    public Add(String filename1, String filename2) {// Reads the states of both machines and initializes the variables with the values stored in the text files.
        initComponents();
        setLocationRelativeTo(null);
        ObjectReader reader=new ObjectReader();
        this.machine1=reader.read(filename1);
        this.products=machine1.getProducts();
        this.coins=machine1.getCoins();
        this.user=machine1.getUser();
        this.coins_introduced.add(0);// 1st position= $5 coins introduced
        this.coins_introduced.add(0);// 2nd position= $10 coins introduced
        this.coins_introduced.add(0);// 3rd position= $20 coins introduced
        System.out.println(machine1.getCoins());
        System.out.println(machine1.getProducts());
        System.out.println(machine1.getUser());
        letrero1.setVisible(false);
        
        ObjectReader reader2=new ObjectReader();
        this.machine2=reader.read2(filename2);
        this.products2=machine2.getProducts();
        this.coins2=machine2.getCoins();
        this.user2=machine2.getUser();
        this.coins_introduced.add(0);// 1st position= $5 coins introduced
        this.coins_introduced.add(0);// 2nd position= $10 coins introduced
        this.coins_introduced.add(0);// 3rd position= $20 coins introduced
        System.out.println(machine2.getCoins());
        System.out.println(machine2.getProducts());
        System.out.println(machine2.getUser());
        letrero2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        letrero2 = new javax.swing.JLabel();
        letrero1 = new javax.swing.JLabel();
        minus18 = new javax.swing.JButton();
        plus18 = new javax.swing.JButton();
        coins18 = new javax.swing.JLabel();
        minus19 = new javax.swing.JButton();
        plus19 = new javax.swing.JButton();
        coins19 = new javax.swing.JLabel();
        minus22 = new javax.swing.JButton();
        plus22 = new javax.swing.JButton();
        coins22 = new javax.swing.JLabel();
        minus23 = new javax.swing.JButton();
        plus23 = new javax.swing.JButton();
        coins23 = new javax.swing.JLabel();
        minus24 = new javax.swing.JButton();
        plus24 = new javax.swing.JButton();
        coins24 = new javax.swing.JLabel();
        minus25 = new javax.swing.JButton();
        plus25 = new javax.swing.JButton();
        coins25 = new javax.swing.JLabel();
        minus26 = new javax.swing.JButton();
        plus26 = new javax.swing.JButton();
        coins26 = new javax.swing.JLabel();
        minus27 = new javax.swing.JButton();
        plus27 = new javax.swing.JButton();
        coins27 = new javax.swing.JLabel();
        minus28 = new javax.swing.JButton();
        plus28 = new javax.swing.JButton();
        coins28 = new javax.swing.JLabel();
        coins17 = new javax.swing.JLabel();
        minus17 = new javax.swing.JButton();
        plus17 = new javax.swing.JButton();
        plus16 = new javax.swing.JButton();
        minus16 = new javax.swing.JButton();
        coins16 = new javax.swing.JLabel();
        minus15 = new javax.swing.JButton();
        plus15 = new javax.swing.JButton();
        coins15 = new javax.swing.JLabel();
        minus14 = new javax.swing.JButton();
        plus14 = new javax.swing.JButton();
        coins14 = new javax.swing.JLabel();
        coins13 = new javax.swing.JLabel();
        plus13 = new javax.swing.JButton();
        minus13 = new javax.swing.JButton();
        plus12 = new javax.swing.JButton();
        coins12 = new javax.swing.JLabel();
        minus12 = new javax.swing.JButton();
        plus9 = new javax.swing.JButton();
        coins9 = new javax.swing.JLabel();
        minus9 = new javax.swing.JButton();
        coins8 = new javax.swing.JLabel();
        plus8 = new javax.swing.JButton();
        minus8 = new javax.swing.JButton();
        minus7 = new javax.swing.JButton();
        plus7 = new javax.swing.JButton();
        coins7 = new javax.swing.JLabel();
        add1 = new javax.swing.JButton();
        add2 = new javax.swing.JButton();
        minus6 = new javax.swing.JButton();
        plus6 = new javax.swing.JButton();
        minus11 = new javax.swing.JButton();
        plus11 = new javax.swing.JButton();
        minus21 = new javax.swing.JButton();
        plus21 = new javax.swing.JButton();
        menu_button = new javax.swing.JButton();
        minus5 = new javax.swing.JButton();
        plus5 = new javax.swing.JButton();
        minus10 = new javax.swing.JButton();
        plus10 = new javax.swing.JButton();
        minus20 = new javax.swing.JButton();
        plus20 = new javax.swing.JButton();
        coins21 = new javax.swing.JLabel();
        coins11 = new javax.swing.JLabel();
        coins6 = new javax.swing.JLabel();
        coins20 = new javax.swing.JLabel();
        coins10 = new javax.swing.JLabel();
        coins5 = new javax.swing.JLabel();
        op18 = new javax.swing.JRadioButton();
        op17 = new javax.swing.JRadioButton();
        op16 = new javax.swing.JRadioButton();
        op15 = new javax.swing.JRadioButton();
        op14 = new javax.swing.JRadioButton();
        op13 = new javax.swing.JRadioButton();
        op12 = new javax.swing.JRadioButton();
        op11 = new javax.swing.JRadioButton();
        op10 = new javax.swing.JRadioButton();
        op9 = new javax.swing.JRadioButton();
        op8 = new javax.swing.JRadioButton();
        op7 = new javax.swing.JRadioButton();
        op6 = new javax.swing.JRadioButton();
        op5 = new javax.swing.JRadioButton();
        op4 = new javax.swing.JRadioButton();
        op3 = new javax.swing.JRadioButton();
        op2 = new javax.swing.JRadioButton();
        op1 = new javax.swing.JRadioButton();
        coin5_image1 = new javax.swing.JLabel();
        coin10_image1 = new javax.swing.JLabel();
        coin20_image1 = new javax.swing.JLabel();
        coin20_image = new javax.swing.JLabel();
        coin10_image = new javax.swing.JLabel();
        coin5_image = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letrero2.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        letrero2.setForeground(new java.awt.Color(255, 255, 255));
        letrero2.setText("The items have been saved!");
        getContentPane().add(letrero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, 250, 30));

        letrero1.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        letrero1.setForeground(new java.awt.Color(255, 255, 255));
        letrero1.setText("The items have been saved!");
        getContentPane().add(letrero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 260, 30));

        minus18.setBackground(new java.awt.Color(51, 77, 157));
        minus18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus18.setForeground(new java.awt.Color(255, 255, 255));
        minus18.setText("-");
        minus18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus18MouseClicked(evt);
            }
        });
        getContentPane().add(minus18, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 40, 30));

        plus18.setBackground(new java.awt.Color(51, 77, 157));
        plus18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus18.setForeground(new java.awt.Color(255, 255, 255));
        plus18.setText("+");
        plus18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus18MouseClicked(evt);
            }
        });
        getContentPane().add(plus18, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 40, 30));

        coins18.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins18.setForeground(new java.awt.Color(255, 255, 255));
        coins18.setText("0");
        getContentPane().add(coins18, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 50, 30));

        minus19.setBackground(new java.awt.Color(51, 77, 157));
        minus19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus19.setForeground(new java.awt.Color(255, 255, 255));
        minus19.setText("-");
        minus19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus19MouseClicked(evt);
            }
        });
        getContentPane().add(minus19, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 40, 30));

        plus19.setBackground(new java.awt.Color(51, 77, 157));
        plus19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus19.setForeground(new java.awt.Color(255, 255, 255));
        plus19.setText("+");
        plus19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus19MouseClicked(evt);
            }
        });
        getContentPane().add(plus19, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, 40, 30));

        coins19.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins19.setForeground(new java.awt.Color(255, 255, 255));
        coins19.setText("0");
        getContentPane().add(coins19, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 150, 50, 30));

        minus22.setBackground(new java.awt.Color(51, 77, 157));
        minus22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus22.setForeground(new java.awt.Color(255, 255, 255));
        minus22.setText("-");
        minus22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus22MouseClicked(evt);
            }
        });
        getContentPane().add(minus22, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 40, 30));

        plus22.setBackground(new java.awt.Color(51, 77, 157));
        plus22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus22.setForeground(new java.awt.Color(255, 255, 255));
        plus22.setText("+");
        plus22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus22MouseClicked(evt);
            }
        });
        getContentPane().add(plus22, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 40, 30));

        coins22.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins22.setForeground(new java.awt.Color(255, 255, 255));
        coins22.setText("0");
        getContentPane().add(coins22, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, 50, 30));

        minus23.setBackground(new java.awt.Color(51, 77, 157));
        minus23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus23.setForeground(new java.awt.Color(255, 255, 255));
        minus23.setText("-");
        minus23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus23MouseClicked(evt);
            }
        });
        getContentPane().add(minus23, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 40, 30));

        plus23.setBackground(new java.awt.Color(51, 77, 157));
        plus23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus23.setForeground(new java.awt.Color(255, 255, 255));
        plus23.setText("+");
        plus23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus23MouseClicked(evt);
            }
        });
        getContentPane().add(plus23, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 40, 30));

        coins23.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins23.setForeground(new java.awt.Color(255, 255, 255));
        coins23.setText("0");
        getContentPane().add(coins23, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, 50, 30));

        minus24.setBackground(new java.awt.Color(51, 77, 157));
        minus24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus24.setForeground(new java.awt.Color(255, 255, 255));
        minus24.setText("-");
        minus24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus24MouseClicked(evt);
            }
        });
        getContentPane().add(minus24, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, 40, 30));

        plus24.setBackground(new java.awt.Color(51, 77, 157));
        plus24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus24.setForeground(new java.awt.Color(255, 255, 255));
        plus24.setText("+");
        plus24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus24MouseClicked(evt);
            }
        });
        getContentPane().add(plus24, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, 40, 30));

        coins24.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins24.setForeground(new java.awt.Color(255, 255, 255));
        coins24.setText("0");
        getContentPane().add(coins24, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 270, 50, 30));

        minus25.setBackground(new java.awt.Color(51, 77, 157));
        minus25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus25.setForeground(new java.awt.Color(255, 255, 255));
        minus25.setText("-");
        minus25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus25MouseClicked(evt);
            }
        });
        getContentPane().add(minus25, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 40, 30));

        plus25.setBackground(new java.awt.Color(51, 77, 157));
        plus25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus25.setForeground(new java.awt.Color(255, 255, 255));
        plus25.setText("+");
        plus25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus25MouseClicked(evt);
            }
        });
        getContentPane().add(plus25, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, 40, 30));

        coins25.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins25.setForeground(new java.awt.Color(255, 255, 255));
        coins25.setText("0");
        getContentPane().add(coins25, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 310, 50, 30));

        minus26.setBackground(new java.awt.Color(51, 77, 157));
        minus26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus26.setForeground(new java.awt.Color(255, 255, 255));
        minus26.setText("-");
        minus26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus26MouseClicked(evt);
            }
        });
        getContentPane().add(minus26, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 40, 30));

        plus26.setBackground(new java.awt.Color(51, 77, 157));
        plus26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus26.setForeground(new java.awt.Color(255, 255, 255));
        plus26.setText("+");
        plus26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus26MouseClicked(evt);
            }
        });
        getContentPane().add(plus26, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, 40, 30));

        coins26.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins26.setForeground(new java.awt.Color(255, 255, 255));
        coins26.setText("0");
        getContentPane().add(coins26, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, 50, 30));

        minus27.setBackground(new java.awt.Color(51, 77, 157));
        minus27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus27.setForeground(new java.awt.Color(255, 255, 255));
        minus27.setText("-");
        minus27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus27MouseClicked(evt);
            }
        });
        getContentPane().add(minus27, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 40, 30));

        plus27.setBackground(new java.awt.Color(51, 77, 157));
        plus27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus27.setForeground(new java.awt.Color(255, 255, 255));
        plus27.setText("+");
        plus27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus27MouseClicked(evt);
            }
        });
        getContentPane().add(plus27, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, 40, 30));

        coins27.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins27.setForeground(new java.awt.Color(255, 255, 255));
        coins27.setText("0");
        getContentPane().add(coins27, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, 50, 30));

        minus28.setBackground(new java.awt.Color(51, 77, 157));
        minus28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus28.setForeground(new java.awt.Color(255, 255, 255));
        minus28.setText("-");
        minus28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus28MouseClicked(evt);
            }
        });
        getContentPane().add(minus28, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 40, 30));

        plus28.setBackground(new java.awt.Color(51, 77, 157));
        plus28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus28.setForeground(new java.awt.Color(255, 255, 255));
        plus28.setText("+");
        plus28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus28MouseClicked(evt);
            }
        });
        getContentPane().add(plus28, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 40, 30));

        coins28.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins28.setForeground(new java.awt.Color(255, 255, 255));
        coins28.setText("0");
        getContentPane().add(coins28, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, 50, 30));

        coins17.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins17.setForeground(new java.awt.Color(255, 255, 255));
        coins17.setText("0");
        getContentPane().add(coins17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 50, 30));

        minus17.setBackground(new java.awt.Color(51, 77, 157));
        minus17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus17.setForeground(new java.awt.Color(255, 255, 255));
        minus17.setText("-");
        minus17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus17MouseClicked(evt);
            }
        });
        getContentPane().add(minus17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 40, 30));

        plus17.setBackground(new java.awt.Color(51, 77, 157));
        plus17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus17.setForeground(new java.awt.Color(255, 255, 255));
        plus17.setText("+");
        plus17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus17MouseClicked(evt);
            }
        });
        getContentPane().add(plus17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 40, 30));

        plus16.setBackground(new java.awt.Color(51, 77, 157));
        plus16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus16.setForeground(new java.awt.Color(255, 255, 255));
        plus16.setText("+");
        plus16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus16MouseClicked(evt);
            }
        });
        getContentPane().add(plus16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 40, 30));

        minus16.setBackground(new java.awt.Color(51, 77, 157));
        minus16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus16.setForeground(new java.awt.Color(255, 255, 255));
        minus16.setText("-");
        minus16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus16MouseClicked(evt);
            }
        });
        getContentPane().add(minus16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 40, 30));

        coins16.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins16.setForeground(new java.awt.Color(255, 255, 255));
        coins16.setText("0");
        getContentPane().add(coins16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 50, 30));

        minus15.setBackground(new java.awt.Color(51, 77, 157));
        minus15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus15.setForeground(new java.awt.Color(255, 255, 255));
        minus15.setText("-");
        minus15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus15MouseClicked(evt);
            }
        });
        getContentPane().add(minus15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 40, 30));

        plus15.setBackground(new java.awt.Color(51, 77, 157));
        plus15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus15.setForeground(new java.awt.Color(255, 255, 255));
        plus15.setText("+");
        plus15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus15MouseClicked(evt);
            }
        });
        getContentPane().add(plus15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 40, 30));

        coins15.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins15.setForeground(new java.awt.Color(255, 255, 255));
        coins15.setText("0");
        getContentPane().add(coins15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 50, 30));

        minus14.setBackground(new java.awt.Color(51, 77, 157));
        minus14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus14.setForeground(new java.awt.Color(255, 255, 255));
        minus14.setText("-");
        minus14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus14MouseClicked(evt);
            }
        });
        getContentPane().add(minus14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 40, 30));

        plus14.setBackground(new java.awt.Color(51, 77, 157));
        plus14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus14.setForeground(new java.awt.Color(255, 255, 255));
        plus14.setText("+");
        plus14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus14MouseClicked(evt);
            }
        });
        getContentPane().add(plus14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 40, 30));

        coins14.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins14.setForeground(new java.awt.Color(255, 255, 255));
        coins14.setText("0");
        getContentPane().add(coins14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 50, 30));

        coins13.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins13.setForeground(new java.awt.Color(255, 255, 255));
        coins13.setText("0");
        getContentPane().add(coins13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 50, 30));

        plus13.setBackground(new java.awt.Color(51, 77, 157));
        plus13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus13.setForeground(new java.awt.Color(255, 255, 255));
        plus13.setText("+");
        plus13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus13MouseClicked(evt);
            }
        });
        getContentPane().add(plus13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 40, 30));

        minus13.setBackground(new java.awt.Color(51, 77, 157));
        minus13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus13.setForeground(new java.awt.Color(255, 255, 255));
        minus13.setText("-");
        minus13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus13MouseClicked(evt);
            }
        });
        getContentPane().add(minus13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 40, 30));

        plus12.setBackground(new java.awt.Color(51, 77, 157));
        plus12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus12.setForeground(new java.awt.Color(255, 255, 255));
        plus12.setText("+");
        plus12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus12MouseClicked(evt);
            }
        });
        getContentPane().add(plus12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 40, 30));

        coins12.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins12.setForeground(new java.awt.Color(255, 255, 255));
        coins12.setText("0");
        getContentPane().add(coins12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 50, 30));

        minus12.setBackground(new java.awt.Color(51, 77, 157));
        minus12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus12.setForeground(new java.awt.Color(255, 255, 255));
        minus12.setText("-");
        minus12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus12MouseClicked(evt);
            }
        });
        getContentPane().add(minus12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 40, 30));

        plus9.setBackground(new java.awt.Color(51, 77, 157));
        plus9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus9.setForeground(new java.awt.Color(255, 255, 255));
        plus9.setText("+");
        plus9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus9MouseClicked(evt);
            }
        });
        getContentPane().add(plus9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 40, 30));

        coins9.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins9.setForeground(new java.awt.Color(255, 255, 255));
        coins9.setText("0");
        getContentPane().add(coins9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 50, 30));

        minus9.setBackground(new java.awt.Color(51, 77, 157));
        minus9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus9.setForeground(new java.awt.Color(255, 255, 255));
        minus9.setText("-");
        minus9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus9MouseClicked(evt);
            }
        });
        getContentPane().add(minus9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 40, 30));

        coins8.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins8.setForeground(new java.awt.Color(255, 255, 255));
        coins8.setText("0");
        getContentPane().add(coins8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 50, 30));

        plus8.setBackground(new java.awt.Color(51, 77, 157));
        plus8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus8.setForeground(new java.awt.Color(255, 255, 255));
        plus8.setText("+");
        plus8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus8MouseClicked(evt);
            }
        });
        getContentPane().add(plus8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 40, 30));

        minus8.setBackground(new java.awt.Color(51, 77, 157));
        minus8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus8.setForeground(new java.awt.Color(255, 255, 255));
        minus8.setText("-");
        minus8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus8MouseClicked(evt);
            }
        });
        getContentPane().add(minus8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 40, 30));

        minus7.setBackground(new java.awt.Color(51, 77, 157));
        minus7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus7.setForeground(new java.awt.Color(255, 255, 255));
        minus7.setText("-");
        minus7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus7MouseClicked(evt);
            }
        });
        getContentPane().add(minus7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 40, 30));

        plus7.setBackground(new java.awt.Color(51, 77, 157));
        plus7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus7.setForeground(new java.awt.Color(255, 255, 255));
        plus7.setText("+");
        plus7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus7MouseClicked(evt);
            }
        });
        getContentPane().add(plus7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 40, 30));

        coins7.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins7.setForeground(new java.awt.Color(255, 255, 255));
        coins7.setText("0");
        getContentPane().add(coins7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 50, 30));

        add1.setBackground(new java.awt.Color(51, 77, 157));
        add1.setFont(new java.awt.Font("Blue Highway", 1, 19)); // NOI18N
        add1.setForeground(new java.awt.Color(255, 255, 255));
        add1.setText("ADD SELECTION");
        add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add1MouseClicked(evt);
            }
        });
        getContentPane().add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 180, 30));

        add2.setBackground(new java.awt.Color(51, 77, 157));
        add2.setFont(new java.awt.Font("Blue Highway", 1, 19)); // NOI18N
        add2.setForeground(new java.awt.Color(255, 255, 255));
        add2.setText("ADD SELECTION");
        add2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add2MouseClicked(evt);
            }
        });
        getContentPane().add(add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, 180, 30));

        minus6.setBackground(new java.awt.Color(51, 77, 157));
        minus6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus6.setForeground(new java.awt.Color(255, 255, 255));
        minus6.setText("-");
        minus6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus6MouseClicked(evt);
            }
        });
        getContentPane().add(minus6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 40, 30));

        plus6.setBackground(new java.awt.Color(51, 77, 157));
        plus6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus6.setForeground(new java.awt.Color(255, 255, 255));
        plus6.setText("+");
        plus6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus6MouseClicked(evt);
            }
        });
        getContentPane().add(plus6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 40, 30));

        minus11.setBackground(new java.awt.Color(51, 77, 157));
        minus11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus11.setForeground(new java.awt.Color(255, 255, 255));
        minus11.setText("-");
        minus11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus11MouseClicked(evt);
            }
        });
        getContentPane().add(minus11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 40, 30));

        plus11.setBackground(new java.awt.Color(51, 77, 157));
        plus11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus11.setForeground(new java.awt.Color(255, 255, 255));
        plus11.setText("+");
        plus11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus11MouseClicked(evt);
            }
        });
        getContentPane().add(plus11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, 40, 30));

        minus21.setBackground(new java.awt.Color(51, 77, 157));
        minus21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus21.setForeground(new java.awt.Color(255, 255, 255));
        minus21.setText("-");
        minus21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus21MouseClicked(evt);
            }
        });
        getContentPane().add(minus21, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, 40, 30));

        plus21.setBackground(new java.awt.Color(51, 77, 157));
        plus21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus21.setForeground(new java.awt.Color(255, 255, 255));
        plus21.setText("+");
        plus21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus21MouseClicked(evt);
            }
        });
        getContentPane().add(plus21, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, 40, 30));

        menu_button.setBackground(new java.awt.Color(51, 77, 157));
        menu_button.setFont(new java.awt.Font("Blue Highway", 1, 19)); // NOI18N
        menu_button.setForeground(new java.awt.Color(255, 255, 255));
        menu_button.setText("MENU");
        menu_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(menu_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, 30));

        minus5.setBackground(new java.awt.Color(51, 77, 157));
        minus5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus5.setForeground(new java.awt.Color(255, 255, 255));
        minus5.setText("-");
        minus5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus5MouseClicked(evt);
            }
        });
        getContentPane().add(minus5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 40, 30));

        plus5.setBackground(new java.awt.Color(51, 77, 157));
        plus5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus5.setForeground(new java.awt.Color(255, 255, 255));
        plus5.setText("+");
        plus5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus5MouseClicked(evt);
            }
        });
        getContentPane().add(plus5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 40, 30));

        minus10.setBackground(new java.awt.Color(51, 77, 157));
        minus10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus10.setForeground(new java.awt.Color(255, 255, 255));
        minus10.setText("-");
        minus10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus10MouseClicked(evt);
            }
        });
        getContentPane().add(minus10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 40, 30));

        plus10.setBackground(new java.awt.Color(51, 77, 157));
        plus10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus10.setForeground(new java.awt.Color(255, 255, 255));
        plus10.setText("+");
        plus10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus10MouseClicked(evt);
            }
        });
        getContentPane().add(plus10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 40, 30));

        minus20.setBackground(new java.awt.Color(51, 77, 157));
        minus20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minus20.setForeground(new java.awt.Color(255, 255, 255));
        minus20.setText("-");
        minus20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus20MouseClicked(evt);
            }
        });
        getContentPane().add(minus20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 40, 30));

        plus20.setBackground(new java.awt.Color(51, 77, 157));
        plus20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plus20.setForeground(new java.awt.Color(255, 255, 255));
        plus20.setText("+");
        plus20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus20MouseClicked(evt);
            }
        });
        getContentPane().add(plus20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 40, 30));

        coins21.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins21.setForeground(new java.awt.Color(255, 255, 255));
        coins21.setText("0");
        getContentPane().add(coins21, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, 50, 30));

        coins11.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins11.setForeground(new java.awt.Color(255, 255, 255));
        coins11.setText("0");
        getContentPane().add(coins11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, 50, 30));

        coins6.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins6.setForeground(new java.awt.Color(255, 255, 255));
        coins6.setText("0");
        getContentPane().add(coins6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 50, 30));

        coins20.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins20.setForeground(new java.awt.Color(255, 255, 255));
        coins20.setText("0");
        getContentPane().add(coins20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 50, 30));

        coins10.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins10.setForeground(new java.awt.Color(255, 255, 255));
        coins10.setText("0");
        getContentPane().add(coins10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 50, 30));

        coins5.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        coins5.setForeground(new java.awt.Color(255, 255, 255));
        coins5.setText("0");
        getContentPane().add(coins5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 50, 30));

        op18.setBackground(new java.awt.Color(0, 102, 153));
        op18.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op18.setForeground(new java.awt.Color(255, 255, 255));
        op18.setText("Earphones");
        getContentPane().add(op18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 200, -1));

        op17.setBackground(new java.awt.Color(0, 102, 153));
        op17.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op17.setForeground(new java.awt.Color(255, 255, 255));
        op17.setText("Cube Charger");
        getContentPane().add(op17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 200, -1));

        op16.setBackground(new java.awt.Color(0, 102, 153));
        op16.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op16.setForeground(new java.awt.Color(255, 255, 255));
        op16.setText("Smart Watch");
        getContentPane().add(op16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 200, -1));

        op15.setBackground(new java.awt.Color(0, 102, 153));
        op15.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op15.setForeground(new java.awt.Color(255, 255, 255));
        op15.setText("Mouse");
        getContentPane().add(op15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 200, -1));

        op14.setBackground(new java.awt.Color(0, 102, 153));
        op14.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op14.setForeground(new java.awt.Color(255, 255, 255));
        op14.setText("Hard Drive ");
        getContentPane().add(op14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 200, -1));

        op13.setBackground(new java.awt.Color(0, 102, 153));
        op13.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op13.setForeground(new java.awt.Color(255, 255, 255));
        op13.setText("USB");
        getContentPane().add(op13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 200, -1));

        op12.setBackground(new java.awt.Color(0, 102, 153));
        op12.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op12.setForeground(new java.awt.Color(255, 255, 255));
        op12.setText("Iphone Case");
        getContentPane().add(op12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 200, -1));

        op11.setBackground(new java.awt.Color(0, 102, 153));
        op11.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op11.setForeground(new java.awt.Color(255, 255, 255));
        op11.setText("USB Cable");
        getContentPane().add(op11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 200, -1));

        op10.setBackground(new java.awt.Color(0, 102, 153));
        op10.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op10.setForeground(new java.awt.Color(255, 255, 255));
        op10.setText("Headphones");
        getContentPane().add(op10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 200, -1));

        op9.setBackground(new java.awt.Color(0, 102, 153));
        op9.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op9.setForeground(new java.awt.Color(255, 255, 255));
        op9.setText("Cranberries");
        getContentPane().add(op9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 200, -1));

        op8.setBackground(new java.awt.Color(0, 102, 153));
        op8.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op8.setForeground(new java.awt.Color(255, 255, 255));
        op8.setText("Vegie Chips");
        getContentPane().add(op8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 200, -1));

        op7.setBackground(new java.awt.Color(0, 102, 153));
        op7.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op7.setForeground(new java.awt.Color(255, 255, 255));
        op7.setText("Cookies");
        getContentPane().add(op7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 200, -1));

        op6.setBackground(new java.awt.Color(0, 102, 153));
        op6.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op6.setForeground(new java.awt.Color(255, 255, 255));
        op6.setText("Baby Carrots");
        getContentPane().add(op6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 200, -1));

        op5.setBackground(new java.awt.Color(0, 102, 153));
        op5.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op5.setForeground(new java.awt.Color(255, 255, 255));
        op5.setText("Protein Bar");
        getContentPane().add(op5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 200, -1));

        op4.setBackground(new java.awt.Color(0, 102, 153));
        op4.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op4.setForeground(new java.awt.Color(255, 255, 255));
        op4.setText("Powerade");
        getContentPane().add(op4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 200, -1));

        op3.setBackground(new java.awt.Color(0, 102, 153));
        op3.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op3.setForeground(new java.awt.Color(255, 255, 255));
        op3.setText("Aloe Water");
        getContentPane().add(op3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 200, -1));

        op2.setBackground(new java.awt.Color(0, 102, 153));
        op2.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op2.setForeground(new java.awt.Color(255, 255, 255));
        op2.setText("Cafe Ole");
        getContentPane().add(op2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 200, -1));

        op1.setBackground(new java.awt.Color(0, 102, 153));
        op1.setFont(new java.awt.Font("Blue Highway", 1, 18)); // NOI18N
        op1.setForeground(new java.awt.Color(255, 255, 255));
        op1.setText("Fiji Water");
        getContentPane().add(op1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 200, -1));

        coin5_image1.setFont(new java.awt.Font("Blue Highway", 1, 22)); // NOI18N
        coin5_image1.setForeground(new java.awt.Color(255, 255, 255));
        coin5_image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/coin5.png"))); // NOI18N
        getContentPane().add(coin5_image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, -1, 60));

        coin10_image1.setFont(new java.awt.Font("Blue Highway", 1, 22)); // NOI18N
        coin10_image1.setForeground(new java.awt.Color(255, 255, 255));
        coin10_image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/coin10.png"))); // NOI18N
        getContentPane().add(coin10_image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, -1, 60));

        coin20_image1.setFont(new java.awt.Font("Blue Highway", 1, 22)); // NOI18N
        coin20_image1.setForeground(new java.awt.Color(255, 255, 255));
        coin20_image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/coin20.png"))); // NOI18N
        getContentPane().add(coin20_image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, -1, 60));

        coin20_image.setFont(new java.awt.Font("Blue Highway", 1, 22)); // NOI18N
        coin20_image.setForeground(new java.awt.Color(255, 255, 255));
        coin20_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/coin20.png"))); // NOI18N
        getContentPane().add(coin20_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, 60));

        coin10_image.setFont(new java.awt.Font("Blue Highway", 1, 22)); // NOI18N
        coin10_image.setForeground(new java.awt.Color(255, 255, 255));
        coin10_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/coin10.png"))); // NOI18N
        getContentPane().add(coin10_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, 60));

        coin5_image.setFont(new java.awt.Font("Blue Highway", 1, 22)); // NOI18N
        coin5_image.setForeground(new java.awt.Color(255, 255, 255));
        coin5_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/coin5.png"))); // NOI18N
        getContentPane().add(coin5_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, 60));

        title1.setFont(new java.awt.Font("Blade Runner Movie Font", 1, 36)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 255, 255));
        title1.setText("TECH");
        getContentPane().add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 120, 30));

        title.setFont(new java.awt.Font("Blade Runner Movie Font", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("add product and money");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 630, 30));

        title3.setFont(new java.awt.Font("Blade Runner Movie Font", 1, 36)); // NOI18N
        title3.setForeground(new java.awt.Color(255, 255, 255));
        title3.setText("food");
        getContentPane().add(title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 120, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/background_add.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_buttonMouseClicked
        Menu menu = new Menu(); // Opens the frame to inctroduce Player names.
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_menu_buttonMouseClicked
    
    // the logic of this method repeats along the class. It updates the number displayed in the 
    //screen but validates if its under 0 so that the screen doesn't display neagtive numbers.
    private void minus5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus5MouseClicked
        if(Integer.parseInt(coins5.getText())-1>=0){
            int num=Integer.parseInt(coins5.getText())-1;
            String info=""+num;
            coins5.setText(info);
        }
    }//GEN-LAST:event_minus5MouseClicked

    private void plus5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus5MouseClicked
        int num=Integer.parseInt(coins5.getText())+1;
        String info=""+num;
        coins5.setText(info);
    }//GEN-LAST:event_plus5MouseClicked

    private void minus10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus10MouseClicked
        if(Integer.parseInt(coins10.getText())-1>=0){
            int num=Integer.parseInt(coins10.getText())-1;
            String info=""+num;
            coins10.setText(info);
        }
    }//GEN-LAST:event_minus10MouseClicked

    private void plus10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus10MouseClicked
        int num=Integer.parseInt(coins10.getText())+1;
        String info=""+num;
        coins10.setText(info);
    }//GEN-LAST:event_plus10MouseClicked

    private void minus20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus20MouseClicked
        if(Integer.parseInt(coins20.getText())-1>=0){
            int num=Integer.parseInt(coins20.getText())-1;
            String info=""+num;
            coins20.setText(info);
        }
    }//GEN-LAST:event_minus20MouseClicked

    private void plus20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus20MouseClicked
        int num=Integer.parseInt(coins20.getText())+1;
        String info=""+num;
        coins20.setText(info);
    }//GEN-LAST:event_plus20MouseClicked

    private void minus6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus6MouseClicked
        if(Integer.parseInt(coins6.getText())-1>=0){
            int num=Integer.parseInt(coins6.getText())-1;
            String info=""+num;
            coins6.setText(info);
        }
    }//GEN-LAST:event_minus6MouseClicked

    private void plus6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus6MouseClicked
        int num=Integer.parseInt(coins6.getText())+1;
        String info=""+num;
        coins6.setText(info);
    }//GEN-LAST:event_plus6MouseClicked

    private void minus11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus11MouseClicked
        if(Integer.parseInt(coins11.getText())-1>=0){
            int num=Integer.parseInt(coins11.getText())-1;
            String info=""+num;
            coins11.setText(info);
        }
    }//GEN-LAST:event_minus11MouseClicked

    private void plus11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus11MouseClicked
        int num=Integer.parseInt(coins11.getText())+1;
        String info=""+num;
        coins11.setText(info);
    }//GEN-LAST:event_plus11MouseClicked

    private void minus21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus21MouseClicked
        if(Integer.parseInt(coins21.getText())-1>=0){
            int num=Integer.parseInt(coins21.getText())-1;
            String info=""+num;
            coins21.setText(info);
        }
    }//GEN-LAST:event_minus21MouseClicked

    private void plus21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus21MouseClicked
        int num=Integer.parseInt(coins21.getText())+1;
        String info=""+num;
        coins21.setText(info);
    }//GEN-LAST:event_plus21MouseClicked

    // adds the products and money selected to the machines.
    private void add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseClicked

      if(op1.isSelected()==true){
          products.get(0).setAvailable(products.get(0).getAvailable()+Integer.parseInt(coins7.getText()));
      }
      
      if(op2.isSelected()==true){
          products.get(1).setAvailable(products.get(1).getAvailable()+Integer.parseInt(coins8.getText()));
      }
      
      if(op3.isSelected()==true){
          products.get(2).setAvailable(products.get(2).getAvailable()+Integer.parseInt(coins9.getText()));
      }
      
      if(op4.isSelected()==true){
          products.get(3).setAvailable(products.get(3).getAvailable()+Integer.parseInt(coins12.getText()));
      }
      
      if(op5.isSelected()==true){
          products.get(4).setAvailable(products.get(4).getAvailable()+Integer.parseInt(coins13.getText()));
      }
      
      if(op6.isSelected()==true){
          products.get(5).setAvailable(products.get(5).getAvailable()+Integer.parseInt(coins14.getText()));
      }
      
      if(op7.isSelected()==true){
          products.get(6).setAvailable(products.get(6).getAvailable()+Integer.parseInt(coins15.getText()));
      }
      
      if(op8.isSelected()==true){
          products.get(7).setAvailable(products.get(7).getAvailable()+Integer.parseInt(coins16.getText()));
      }
      
      if(op9.isSelected()==true){
          products.get(8).setAvailable(products.get(8).getAvailable()+Integer.parseInt(coins17.getText()));
      }
      
      coins.set(1,coins.get(1)+Integer.parseInt(coins5.getText()));
      coins.set(2,coins.get(2)+Integer.parseInt(coins10.getText()));
      coins.set(3,coins.get(3)+Integer.parseInt(coins20.getText()));
      coins.set(0,coins.get(1)*5+coins.get(2)*10+coins.get(3)*20);
      
        machine1.setProducts(products);
        machine1.setUser(user);
        machine1.setCoins(coins);
        
        String filename=""; // saves the state of the machine
        filename="machine2.txt";
        machine_writer.writer(machine1, filename);
      
      letrero1.setVisible(true);
      add1.setVisible(false);
    }//GEN-LAST:event_add1MouseClicked

    private void add2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add2MouseClicked
        if(op10.isSelected()==true){
          products2.get(0).setAvailable(products2.get(0).getAvailable()+Integer.parseInt(coins18.getText()));
      }
      
      if(op11.isSelected()==true){
          products2.get(1).setAvailable(products2.get(1).getAvailable()+Integer.parseInt(coins19.getText()));
      }
      
      if(op12.isSelected()==true){
          products2.get(2).setAvailable(products2.get(2).getAvailable()+Integer.parseInt(coins22.getText()));
      }
      
      if(op13.isSelected()==true){
          products2.get(3).setAvailable(products2.get(3).getAvailable()+Integer.parseInt(coins23.getText()));
      }
      
      if(op14.isSelected()==true){
          products2.get(4).setAvailable(products2.get(4).getAvailable()+Integer.parseInt(coins24.getText()));
      }
      
      if(op15.isSelected()==true){
          products2.get(5).setAvailable(products2.get(5).getAvailable()+Integer.parseInt(coins25.getText()));
      }
      
      if(op16.isSelected()==true){
          products2.get(6).setAvailable(products2.get(6).getAvailable()+Integer.parseInt(coins26.getText()));
      }
      
      if(op17.isSelected()==true){
          products2.get(7).setAvailable(products2.get(7).getAvailable()+Integer.parseInt(coins27.getText()));
      }
      
      if(op18.isSelected()==true){
          products2.get(8).setAvailable(products.get(8).getAvailable()+Integer.parseInt(coins28.getText()));
      }
      
      coins.set(1,coins.get(1)+Integer.parseInt(coins5.getText()));
      coins.set(2,coins.get(2)+Integer.parseInt(coins10.getText()));
      coins.set(3,coins.get(3)+Integer.parseInt(coins20.getText()));
      coins.set(0,coins.get(1)*5+coins.get(2)*10+coins.get(3)*20);
      
        machine1.setProducts(products);
        machine1.setUser(user);
        machine1.setCoins(coins);
        
        String filename2=""; // saves the state of the machine
        filename2="machine3.txt";
        machine_writer.writer2(machine2, filename2);
      
      letrero2.setVisible(true);
      add2.setVisible(false);
    }//GEN-LAST:event_add2MouseClicked

    private void minus7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus7MouseClicked
        if(Integer.parseInt(coins7.getText())-1>=0){
            int num=Integer.parseInt(coins7.getText())-1;
            String info=""+num;
            coins7.setText(info);
        }
    }//GEN-LAST:event_minus7MouseClicked

    private void plus7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus7MouseClicked
        int num=Integer.parseInt(coins7.getText())+1;
        String info=""+num;
        coins7.setText(info);
    }//GEN-LAST:event_plus7MouseClicked

    private void plus8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus8MouseClicked
        int num=Integer.parseInt(coins8.getText())+1;
        String info=""+num;
        coins8.setText(info);
    }//GEN-LAST:event_plus8MouseClicked

    private void minus8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus8MouseClicked
        if(Integer.parseInt(coins8.getText())-1>=0){
            int num=Integer.parseInt(coins8.getText())-1;
            String info=""+num;
            coins8.setText(info);
        }
    }//GEN-LAST:event_minus8MouseClicked

    private void plus9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus9MouseClicked
        int num=Integer.parseInt(coins9.getText())+1;
        String info=""+num;
        coins9.setText(info);
    }//GEN-LAST:event_plus9MouseClicked

    private void minus9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus9MouseClicked
        if(Integer.parseInt(coins9.getText())-1>=0){
            int num=Integer.parseInt(coins9.getText())-1;
            String info=""+num;
            coins9.setText(info);
        }
    }//GEN-LAST:event_minus9MouseClicked

    private void plus12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus12MouseClicked
        int num=Integer.parseInt(coins12.getText())+1;
        String info=""+num;
        coins12.setText(info);
    }//GEN-LAST:event_plus12MouseClicked

    private void minus12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus12MouseClicked
        if(Integer.parseInt(coins12.getText())-1>=0){
            int num=Integer.parseInt(coins12.getText())-1;
            String info=""+num;
            coins12.setText(info);
        }
    }//GEN-LAST:event_minus12MouseClicked

    private void plus13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus13MouseClicked
        int num=Integer.parseInt(coins13.getText())+1;
        String info=""+num;
        coins13.setText(info);
    }//GEN-LAST:event_plus13MouseClicked

    private void minus13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus13MouseClicked
        if(Integer.parseInt(coins13.getText())-1>=0){
            int num=Integer.parseInt(coins13.getText())-1;
            String info=""+num;
            coins13.setText(info);
        }
    }//GEN-LAST:event_minus13MouseClicked

    private void minus14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus14MouseClicked
        if(Integer.parseInt(coins14.getText())-1>=0){
            int num=Integer.parseInt(coins14.getText())-1;
            String info=""+num;
            coins14.setText(info);
        }
    }//GEN-LAST:event_minus14MouseClicked

    private void plus14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus14MouseClicked
        int num=Integer.parseInt(coins14.getText())+1;
        String info=""+num;
        coins14.setText(info);
    }//GEN-LAST:event_plus14MouseClicked

    private void minus15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus15MouseClicked
        if(Integer.parseInt(coins15.getText())-1>=0){
            int num=Integer.parseInt(coins15.getText())-1;
            String info=""+num;
            coins15.setText(info);
        }
    }//GEN-LAST:event_minus15MouseClicked

    private void plus15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus15MouseClicked
        int num=Integer.parseInt(coins15.getText())+1;
        String info=""+num;
        coins15.setText(info);
    }//GEN-LAST:event_plus15MouseClicked

    private void plus16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus16MouseClicked
        int num=Integer.parseInt(coins16.getText())+1;
        String info=""+num;
        coins16.setText(info);
    }//GEN-LAST:event_plus16MouseClicked

    private void minus16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus16MouseClicked
        if(Integer.parseInt(coins16.getText())-1>=0){
            int num=Integer.parseInt(coins16.getText())-1;
            String info=""+num;
            coins16.setText(info);
        }
    }//GEN-LAST:event_minus16MouseClicked

    private void minus17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus17MouseClicked
        if(Integer.parseInt(coins17.getText())-1>=0){
            int num=Integer.parseInt(coins17.getText())-1;
            String info=""+num;
            coins17.setText(info);
        }
    }//GEN-LAST:event_minus17MouseClicked

    private void plus17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus17MouseClicked
        int num=Integer.parseInt(coins17.getText())+1;
        String info=""+num;
        coins17.setText(info);
    }//GEN-LAST:event_plus17MouseClicked

    private void minus18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus18MouseClicked
        if(Integer.parseInt(coins18.getText())-1>=0){
            int num=Integer.parseInt(coins18.getText())-1;
            String info=""+num;
            coins18.setText(info);
        }
    }//GEN-LAST:event_minus18MouseClicked

    private void plus18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus18MouseClicked
        int num=Integer.parseInt(coins18.getText())+1;
        String info=""+num;
        coins18.setText(info);
    }//GEN-LAST:event_plus18MouseClicked

    private void minus19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus19MouseClicked
        if(Integer.parseInt(coins19.getText())-1>=0){
            int num=Integer.parseInt(coins19.getText())-1;
            String info=""+num;
            coins19.setText(info);
        }
    }//GEN-LAST:event_minus19MouseClicked

    private void plus19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus19MouseClicked
        int num=Integer.parseInt(coins19.getText())+1;
        String info=""+num;
        coins19.setText(info);
    }//GEN-LAST:event_plus19MouseClicked

    private void minus22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus22MouseClicked
        if(Integer.parseInt(coins22.getText())-1>=0){
            int num=Integer.parseInt(coins22.getText())-1;
            String info=""+num;
            coins22.setText(info);
        }
    }//GEN-LAST:event_minus22MouseClicked

    private void plus22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus22MouseClicked
        int num=Integer.parseInt(coins22.getText())+1;
        String info=""+num;
        coins22.setText(info);
    }//GEN-LAST:event_plus22MouseClicked

    private void minus23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus23MouseClicked
        if(Integer.parseInt(coins23.getText())-1>=0){
            int num=Integer.parseInt(coins23.getText())-1;
            String info=""+num;
            coins23.setText(info);
        }
    }//GEN-LAST:event_minus23MouseClicked

    private void plus23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus23MouseClicked
        int num=Integer.parseInt(coins23.getText())+1;
        String info=""+num;
        coins23.setText(info);
    }//GEN-LAST:event_plus23MouseClicked

    private void minus24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus24MouseClicked
        if(Integer.parseInt(coins24.getText())-1>=0){
            int num=Integer.parseInt(coins24.getText())-1;
            String info=""+num;
            coins24.setText(info);
        }
    }//GEN-LAST:event_minus24MouseClicked

    private void plus24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus24MouseClicked
        int num=Integer.parseInt(coins24.getText())+1;
        String info=""+num;
        coins24.setText(info);
    }//GEN-LAST:event_plus24MouseClicked

    private void minus25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus25MouseClicked
        if(Integer.parseInt(coins25.getText())-1>=0){
            int num=Integer.parseInt(coins25.getText())-1;
            String info=""+num;
            coins25.setText(info);
        }
    }//GEN-LAST:event_minus25MouseClicked

    private void plus25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus25MouseClicked
        int num=Integer.parseInt(coins25.getText())+1;
        String info=""+num;
        coins25.setText(info);
    }//GEN-LAST:event_plus25MouseClicked

    private void minus26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus26MouseClicked
        if(Integer.parseInt(coins26.getText())-1>=0){
            int num=Integer.parseInt(coins26.getText())-1;
            String info=""+num;
            coins26.setText(info);
        }
    }//GEN-LAST:event_minus26MouseClicked

    private void plus26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus26MouseClicked
        int num=Integer.parseInt(coins26.getText())+1;
        String info=""+num;
        coins26.setText(info);
    }//GEN-LAST:event_plus26MouseClicked

    private void minus27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus27MouseClicked
        if(Integer.parseInt(coins27.getText())-1>=0){
            int num=Integer.parseInt(coins27.getText())-1;
            String info=""+num;
            coins27.setText(info);
        }
    }//GEN-LAST:event_minus27MouseClicked

    private void plus27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus27MouseClicked
        int num=Integer.parseInt(coins27.getText())+1;
        String info=""+num;
        coins27.setText(info);
    }//GEN-LAST:event_plus27MouseClicked

    private void minus28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus28MouseClicked
        if(Integer.parseInt(coins28.getText())-1>=0){
            int num=Integer.parseInt(coins28.getText())-1;
            String info=""+num;
            coins28.setText(info);
        }
    }//GEN-LAST:event_minus28MouseClicked

    private void plus28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus28MouseClicked
        int num=Integer.parseInt(coins28.getText())+1;
        String info=""+num;
        coins28.setText(info);
    }//GEN-LAST:event_plus28MouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add1;
    private javax.swing.JButton add2;
    private javax.swing.JLabel background;
    private javax.swing.JLabel coin10_image;
    private javax.swing.JLabel coin10_image1;
    private javax.swing.JLabel coin20_image;
    private javax.swing.JLabel coin20_image1;
    private javax.swing.JLabel coin5_image;
    private javax.swing.JLabel coin5_image1;
    private javax.swing.JLabel coins10;
    private javax.swing.JLabel coins11;
    private javax.swing.JLabel coins12;
    private javax.swing.JLabel coins13;
    private javax.swing.JLabel coins14;
    private javax.swing.JLabel coins15;
    private javax.swing.JLabel coins16;
    private javax.swing.JLabel coins17;
    private javax.swing.JLabel coins18;
    private javax.swing.JLabel coins19;
    private javax.swing.JLabel coins20;
    private javax.swing.JLabel coins21;
    private javax.swing.JLabel coins22;
    private javax.swing.JLabel coins23;
    private javax.swing.JLabel coins24;
    private javax.swing.JLabel coins25;
    private javax.swing.JLabel coins26;
    private javax.swing.JLabel coins27;
    private javax.swing.JLabel coins28;
    private javax.swing.JLabel coins5;
    private javax.swing.JLabel coins6;
    private javax.swing.JLabel coins7;
    private javax.swing.JLabel coins8;
    private javax.swing.JLabel coins9;
    private javax.swing.JLabel letrero1;
    private javax.swing.JLabel letrero2;
    private javax.swing.JButton menu_button;
    private javax.swing.JButton minus10;
    private javax.swing.JButton minus11;
    private javax.swing.JButton minus12;
    private javax.swing.JButton minus13;
    private javax.swing.JButton minus14;
    private javax.swing.JButton minus15;
    private javax.swing.JButton minus16;
    private javax.swing.JButton minus17;
    private javax.swing.JButton minus18;
    private javax.swing.JButton minus19;
    private javax.swing.JButton minus20;
    private javax.swing.JButton minus21;
    private javax.swing.JButton minus22;
    private javax.swing.JButton minus23;
    private javax.swing.JButton minus24;
    private javax.swing.JButton minus25;
    private javax.swing.JButton minus26;
    private javax.swing.JButton minus27;
    private javax.swing.JButton minus28;
    private javax.swing.JButton minus5;
    private javax.swing.JButton minus6;
    private javax.swing.JButton minus7;
    private javax.swing.JButton minus8;
    private javax.swing.JButton minus9;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op10;
    private javax.swing.JRadioButton op11;
    private javax.swing.JRadioButton op12;
    private javax.swing.JRadioButton op13;
    private javax.swing.JRadioButton op14;
    private javax.swing.JRadioButton op15;
    private javax.swing.JRadioButton op16;
    private javax.swing.JRadioButton op17;
    private javax.swing.JRadioButton op18;
    private javax.swing.JRadioButton op2;
    private javax.swing.JRadioButton op3;
    private javax.swing.JRadioButton op4;
    private javax.swing.JRadioButton op5;
    private javax.swing.JRadioButton op6;
    private javax.swing.JRadioButton op7;
    private javax.swing.JRadioButton op8;
    private javax.swing.JRadioButton op9;
    private javax.swing.JButton plus10;
    private javax.swing.JButton plus11;
    private javax.swing.JButton plus12;
    private javax.swing.JButton plus13;
    private javax.swing.JButton plus14;
    private javax.swing.JButton plus15;
    private javax.swing.JButton plus16;
    private javax.swing.JButton plus17;
    private javax.swing.JButton plus18;
    private javax.swing.JButton plus19;
    private javax.swing.JButton plus20;
    private javax.swing.JButton plus21;
    private javax.swing.JButton plus22;
    private javax.swing.JButton plus23;
    private javax.swing.JButton plus24;
    private javax.swing.JButton plus25;
    private javax.swing.JButton plus26;
    private javax.swing.JButton plus27;
    private javax.swing.JButton plus28;
    private javax.swing.JButton plus5;
    private javax.swing.JButton plus6;
    private javax.swing.JButton plus7;
    private javax.swing.JButton plus8;
    private javax.swing.JButton plus9;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title3;
    // End of variables declaration//GEN-END:variables
}
